create table public.expenditure_type (
  id smallint generated by default as identity not null,
  name text not null,
  id_admin uuid not null default gen_random_uuid (),
  constraint expenditure_type_pkey primary key (id),
  constraint expenditure_type_id_admin_fkey foreign KEY (id_admin) references admin (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;