create table public.expenditure (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  by_email text not null default auth.email (),
  note text not null,
  id_admin uuid not null,
  id_expenditure_type smallint not null,
  constraint expenditure_pkey primary key (id),
  constraint expenditure_id_admin_fkey foreign KEY (id_admin) references admin (id) on update CASCADE on delete CASCADE,
  constraint expenditure_id_expenditure_type_fkey foreign KEY (id_expenditure_type) references expenditure_type (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;