create table public.history (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  by_email text not null default auth.email (),
  note text not null,
  id_admin uuid not null,
  constraint history_pkey primary key (id),
  constraint history_id_admin_fkey foreign KEY (id_admin) references admin (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;