create table public.salary (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  id_admin uuid not null default gen_random_uuid (),
  amount numeric not null,
  month smallint not null,
  is_paid boolean not null,
  paid_at date null,
  by_email text not null default auth.email (),
  to_email text not null,
  constraint salary_pkey primary key (id),
  constraint salary_id_admin_fkey foreign KEY (id_admin) references admin (id) on update CASCADE on delete CASCADE,
  constraint salary_to_email_fkey foreign KEY (to_email) references staff (email) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;