create table public.staff_permission (
  id bigint generated by default as identity not null,
  id_access_list smallint not null,
  email_staff text not null,
  constraint staff_permission_pkey primary key (id),
  constraint staff_permission_email_staff_fkey foreign KEY (email_staff) references staff (email) on update CASCADE on delete CASCADE,
  constraint staff_permission_id_access_list_fkey foreign KEY (id_access_list) references access_list (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;